// The one definition of our security headers. next.config.ts uses it for the server build and
// scripts/build-headers.mjs writes the same thing into public/_headers for Cloudflare Pages,
// which serves a static export and so gets no headers from Next at all.
import { firstUrl } from "./photo-sources.mjs";

// Cloudflare Pages reads at most this many characters on one line of _headers.
export const HEADERS_LINE_LIMIT = 2000;

export function buildHeaders({ apiOrigin, isDev = false }) {
  // Next's App Router hydrates through inline <script> tags it writes itself, so script-src needs
  // 'unsafe-inline'; a nonce would force every page to render per request and the landing page
  // must stay static. 'unsafe-eval' is development only. Styles come from our own CSS files only.
  // An empty apiOrigin means the API is served under /api/* on this same origin (Update 10 A1),
  // so the browser may connect to 'self' and nowhere else.
  const connect = apiOrigin ? `connect-src 'self' ${apiOrigin}` : "connect-src 'self'";
  const csp = [
    "default-src 'self'",
    `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ""}`,
    `style-src 'self'${isDev ? " 'unsafe-inline'" : ""}`,
    "img-src 'self' data: blob:",
    connect,
    "font-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "manifest-src 'self'",
    "worker-src 'self'",
  ].join("; ");

  const everywhere = [
    { key: "Content-Security-Policy", value: csp },
    { key: "Referrer-Policy", value: "no-referrer" },
    { key: "X-Content-Type-Options", value: "nosniff" },
    { key: "X-Frame-Options", value: "DENY" },
    { key: "Permissions-Policy", value: "geolocation=(), camera=(), microphone=(), payment=(), usb=()" },
  ];

  // Only the creek check and the quick return check ask for location or a camera photo.
  const fieldPermissions = { key: "Permissions-Policy", value: "geolocation=(self), camera=(self), microphone=(), payment=(), usb=()" };

  return { csp, everywhere, fieldPermissions };
}

/**
 * The pages that preload photos, and which. The landing page and the poster show the two warm-up
 * photos first. Pages turns a Link header into an Early Hint, so the photos start loading before
 * the page arrives. Pages used to write these headers itself from the page's own preload tags,
 * but stopped once the project gained the /api Functions, and the first screen got slower.
 */
export function photoPreloads(content) {
  const links = (content?.warmup ?? []).slice(0, 2).map((w) => photoPreload(content?.photos?.[w.photo_id])).filter(Boolean);
  return links.length ? { "/": links, "/poster": links } : {};
}

/**
 * One preload per photo. A photo with smaller copies preloads its AVIF set exactly as the page's
 * own preload tag does: imagesrcset and imagesizes, so the browser fetches only the copy it will
 * show, and type, so a browser without AVIF fetches none of them, and no phone gets the JPEG too.
 * Chrome skips a preload like this in a 103 Early Hint and acts on it once the page's own response
 * arrives. A photo without copies keeps the plain preload of its URL.
 */
export function photoPreload(photo) {
  if (!photo?.url) return null;
  const avif = (photo.sources ?? []).find((s) => s.type === "image/avif");
  if (!avif) return { href: photo.url };
  return { href: firstUrl(avif.srcset), type: avif.type, imagesrcset: avif.srcset, imagesizes: photo.sizes };
}

/** One Link header entry. The attributes go in quotes, because a srcset holds commas. */
export function linkEntry(entry) {
  const { href, type, imagesrcset, imagesizes } = typeof entry === "string" ? { href: entry } : entry;
  const quoted = (name, value) => {
    if (/["\r\n]/.test(value)) throw new Error(`a Link ${name} cannot hold quotes or line breaks: ${value}`);
    return `; ${name}="${value}"`;
  };
  return (
    `<${href}>; rel=preload; as=image` +
    (type ? quoted("type", type) : "") +
    (imagesrcset ? quoted("imagesrcset", imagesrcset) : "") +
    (imagesizes ? quoted("imagesizes", imagesizes) : "")
  );
}

/** The Cloudflare Pages _headers format: a path, then one indented header line each. */
export function headersFile({ apiOrigin, preloads = {} }) {
  const { everywhere, fieldPermissions } = buildHeaders({ apiOrigin });
  const block = (path, list) => `${path}\n${list.map((h) => `  ${h.key}: ${h.value}`).join("\n")}\n`;
  const link = (entries) => ({ key: "Link", value: entries.map(linkEntry).join(", ") });
  const text = [
    "# Generated by scripts/build-headers.mjs from security-headers.mjs. Do not edit by hand.",
    "",
    block("/*", everywhere),
    ...Object.entries(preloads).map(([path, urls]) => block(path, [link(urls)])),
    block("/check", [fieldPermissions]),
    block("/quick", [fieldPermissions]),
    "/sw.js\n  Cache-Control: no-cache\n",
    // The share cards are written as extensionless files by the static export, so Pages would
    // guess application/octet-stream and no chat window would render the preview.
    "/api/share/*\n  Content-Type: image/svg+xml; charset=utf-8\n",
  ].join("\n");
  // Pages drops a longer line without a word, and the Early Hints with it.
  const long = text.split("\n").find((line) => line.length > HEADERS_LINE_LIMIT);
  if (long) throw new Error(`a _headers line is ${long.length} characters, over the ${HEADERS_LINE_LIMIT} Pages reads: ${long.slice(0, 80)}`);
  return text;
}
