// The one definition of our security headers. next.config.ts uses it for the server build and
// scripts/build-headers.mjs writes the same thing into public/_headers for Cloudflare Pages,
// which serves a static export and so gets no headers from Next at all.

export function buildHeaders({ apiOrigin, isDev = false }) {
  // Next's App Router hydrates through inline <script> tags it writes itself, so script-src needs
  // 'unsafe-inline'; a nonce would force every page to render per request and the landing page
  // must stay static. 'unsafe-eval' is development only. Styles come from our own CSS files only.
  const csp = [
    "default-src 'self'",
    `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ""}`,
    `style-src 'self'${isDev ? " 'unsafe-inline'" : ""}`,
    "img-src 'self' data: blob:",
    `connect-src 'self' ${apiOrigin}`,
    "font-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "manifest-src 'self'",
    "worker-src 'self'",
  ].join("; ");

  const everywhere = [
    { key: "Content-Security-Policy", value: csp },
    { key: "Referrer-Policy", value: "no-referrer" },
    { key: "X-Content-Type-Options", value: "nosniff" },
    { key: "X-Frame-Options", value: "DENY" },
    { key: "Permissions-Policy", value: "geolocation=(), camera=(), microphone=(), payment=(), usb=()" },
  ];

  // Only the creek check and the quick return check ask for location or a camera photo.
  const fieldPermissions = { key: "Permissions-Policy", value: "geolocation=(self), camera=(self), microphone=(), payment=(), usb=()" };

  return { csp, everywhere, fieldPermissions };
}

/** The Cloudflare Pages _headers format: a path, then one indented header line each. */
export function headersFile({ apiOrigin }) {
  const { everywhere, fieldPermissions } = buildHeaders({ apiOrigin });
  const block = (path, list) => `${path}\n${list.map((h) => `  ${h.key}: ${h.value}`).join("\n")}\n`;
  return [
    "# Generated by scripts/build-headers.mjs from security-headers.mjs. Do not edit by hand.",
    "",
    block("/*", everywhere),
    block("/check", [fieldPermissions]),
    block("/quick", [fieldPermissions]),
    "/sw.js\n  Cache-Control: no-cache\n",
    // The share cards are written as extensionless files by the static export, so Pages would
    // guess application/octet-stream and no chat window would render the preview.
    "/api/share/*\n  Content-Type: image/svg+xml; charset=utf-8\n",
  ].join("\n");
}
