// The one definition of our security headers. next.config.ts uses it for the server build and
// scripts/build-headers.mjs writes the same thing into public/_headers for Cloudflare Pages,
// which serves a static export and so gets no headers from Next at all.

export function buildHeaders({ apiOrigin, isDev = false }) {
  // Next's App Router hydrates through inline <script> tags it writes itself, so script-src needs
  // 'unsafe-inline'; a nonce would force every page to render per request and the landing page
  // must stay static. 'unsafe-eval' is development only. Styles come from our own CSS files only.
  // An empty apiOrigin means the API is served under /api/* on this same origin (Update 10 A1),
  // so the browser may connect to 'self' and nowhere else.
  const connect = apiOrigin ? `connect-src 'self' ${apiOrigin}` : "connect-src 'self'";
  const csp = [
    "default-src 'self'",
    `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ""}`,
    `style-src 'self'${isDev ? " 'unsafe-inline'" : ""}`,
    "img-src 'self' data: blob:",
    connect,
    "font-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "manifest-src 'self'",
    "worker-src 'self'",
  ].join("; ");

  const everywhere = [
    { key: "Content-Security-Policy", value: csp },
    { key: "Referrer-Policy", value: "no-referrer" },
    { key: "X-Content-Type-Options", value: "nosniff" },
    { key: "X-Frame-Options", value: "DENY" },
    { key: "Permissions-Policy", value: "geolocation=(), camera=(), microphone=(), payment=(), usb=()" },
  ];

  // Only the creek check and the quick return check ask for location or a camera photo.
  const fieldPermissions = { key: "Permissions-Policy", value: "geolocation=(self), camera=(self), microphone=(), payment=(), usb=()" };

  return { csp, everywhere, fieldPermissions };
}

/** The Cloudflare Pages _headers format: a path, then one indented header line each. */
/**
 * The pages that preload photos, and which. The landing page and the poster show the two warm-up
 * photos first. Pages turns a Link header into an Early Hint, so the photos start loading before
 * the page arrives. Pages used to write these headers itself from the page's own preload tags,
 * but stopped once the project gained the /api Functions, and the first screen got slower.
 */
export function photoPreloads(content) {
  const urls = (content?.warmup ?? []).slice(0, 2).map((w) => content?.photos?.[w.photo_id]?.url).filter(Boolean);
  return urls.length ? { "/": urls, "/poster": urls } : {};
}

export function headersFile({ apiOrigin, preloads = {} }) {
  const { everywhere, fieldPermissions } = buildHeaders({ apiOrigin });
  const block = (path, list) => `${path}\n${list.map((h) => `  ${h.key}: ${h.value}`).join("\n")}\n`;
  const link = (urls) => ({ key: "Link", value: urls.map((u) => `<${u}>; rel=preload; as=image`).join(", ") });
  return [
    "# Generated by scripts/build-headers.mjs from security-headers.mjs. Do not edit by hand.",
    "",
    block("/*", everywhere),
    ...Object.entries(preloads).map(([path, urls]) => block(path, [link(urls)])),
    block("/check", [fieldPermissions]),
    block("/quick", [fieldPermissions]),
    "/sw.js\n  Cache-Control: no-cache\n",
    // The share cards are written as extensionless files by the static export, so Pages would
    // guess application/octet-stream and no chat window would render the preview.
    "/api/share/*\n  Content-Type: image/svg+xml; charset=utf-8\n",
  ].join("\n");
}
