// Generates components/ui/Icon.tsx from @phosphor-icons/core so the product has exactly one icon
// family, no icon runtime in the bundle, and no hand drawn SVG. Run `npm run icons` after adding a
// name below. The generated file is committed; the package stays a devDependency.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, "..");
const assets = join(webRoot, "node_modules", "@phosphor-icons", "core", "assets", "regular");
const out = join(webRoot, "components", "ui", "Icon.tsx");

// Every icon the product uses. Adding one here is the only way to add an icon.
const NAMES = ["check-circle", "warning", "warning-circle", "info", "x", "magnifying-glass-plus", "caret-left", "wifi-slash"];

function pathsFor(name) {
  const file = join(assets, `${name}.svg`);
  if (!existsSync(file)) {
    console.error(`build-icons: no such Phosphor icon ${name}`);
    process.exit(1);
  }
  const svg = readFileSync(file, "utf8");
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (ds.length === 0) {
    console.error(`build-icons: ${name} has no path data`);
    process.exit(1);
  }
  return ds;
}

const entries = NAMES.map((n) => `  "${n}": [${pathsFor(n).map((d) => JSON.stringify(d)).join(", ")}],`).join("\n");

const body = `// GENERATED by scripts/build-icons.mjs from @phosphor-icons/core (MIT). Do not edit by hand.
// One family, regular weight. Decorative by default; pass a label to expose it to a screen reader.

const PATHS: Record<string, string[]> = {
${entries}
};

export type IconName = keyof typeof PATHS;

export function Icon({ name, label, size = 24 }: { name: IconName; label?: string; size?: number }) {
  const paths = PATHS[name];
  if (!paths) return null;
  return (
    <svg
      className="icon"
      viewBox="0 0 256 256"
      width={size}
      height={size}
      fill="currentColor"
      focusable="false"
      role={label ? "img" : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
    >
      {paths.map((d) => (
        <path key={d} d={d} />
      ))}
    </svg>
  );
}
`;

writeFileSync(out, body);
console.log(`build-icons: wrote ${NAMES.length} Phosphor icons into components/ui/Icon.tsx`);
