"""Write the pre-registered arm sequence into a SQL file for D1.

core/allocator.py is the single source of truth for randomization and it uses Python's random,
which cannot be ported to a Worker without risking a different sequence. So the sequence is
computed here and loaded into D1, and the Worker only takes the next slot. `core.allocator.replay`
still checks every stored assignment, which is what the analysis plan promises.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from core.allocator import arm_for_position

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "worker" / "arms.sql"


def sql_for(seed: str, count: int) -> str:
    lines = [
        "-- Generated by scripts/seed_arms.py from core/allocator.py. Do not edit by hand.",
        f"-- seed {seed}, {count} slots",
        "DELETE FROM arm_slot;",
    ]
    for position in range(count):
        arm, block_id = arm_for_position(seed, position)
        values = f"({position}, '{arm}', {block_id})"
        lines.append(f"INSERT INTO arm_slot (position, arm, block_id) VALUES {values};")
    lines.append("INSERT OR IGNORE INTO counter (id, next_position) VALUES (1, 0);")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", required=True, help="the stored randomization seed")
    parser.add_argument("--count", type=int, default=2000, help="how many slots to write")
    args = parser.parse_args(argv)
    if args.count < 1:
        raise SystemExit("seed-arms: count must be at least 1")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(sql_for(args.seed, args.count), encoding="utf-8")
    print(f"seed-arms: wrote {args.count} slots for seed {args.seed} into {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
