"""Write part 2's pre-registered arm sequences into worker/part2_arms.sql for D1.

Permuted blocks of 4, stratified by part 1 arm (docs/analysis_plan_v2.md item 2): one sequence
per part 1 arm, each from core/allocator.py with its own stored seed. The allocator names its two
arms untrained and trained; this file writes them as unassisted and assisted through
core.assist.ALLOCATOR_TO_PART2, so the allocator stays the one source of randomization and
core.allocator.replay still checks every stored assignment.

Run: uv run python scripts/seed_part2_arms.py [--count 1000]
"""

from __future__ import annotations

import argparse
from pathlib import Path

from core.allocator import arm_for_position
from core.assist import ALLOCATOR_TO_PART2

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "worker" / "part2_arms.sql"
SEED_PREFIX = "second-look-part2-20260926"
STRATA = ("untrained", "trained")


def seed_for(stratum: str) -> str:
    return f"{SEED_PREFIX}-{stratum}"


def sql_for(count: int) -> str:
    lines = [
        "-- Generated by scripts/seed_part2_arms.py from core/allocator.py. Do not edit by hand.",
        f"-- seeds {', '.join(seed_for(s) for s in STRATA)}, {count} slots each",
        "DELETE FROM part2_slot;",
    ]
    for stratum in STRATA:
        for position in range(count):
            slot, block_id = arm_for_position(seed_for(stratum), position)
            arm = ALLOCATOR_TO_PART2[slot]
            lines.append(
                "INSERT INTO part2_slot (stratum, position, arm, block_id) "
                f"VALUES ('{stratum}', {position}, '{arm}', {block_id});"
            )
        lines.append(
            f"INSERT OR IGNORE INTO part2_counter (stratum, next_position) VALUES ('{stratum}', 0);"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=1000, help="slots per part 1 arm")
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args(argv)
    text = sql_for(args.count)
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("seed-part2-arms: worker/part2_arms.sql is stale")
            return 1
        print("seed-part2-arms: worker/part2_arms.sql is current")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"seed-part2-arms: wrote {args.count} slots per part 1 arm into {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
